### Check
GET http://localhost:5000/ HTTP/1.1

### Register
POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
    "id" : 1,
    "imageUrls" : "profile.imageUrls",
    "name" : "profile.name",
    "email" : "profile.email",
    "password" : "profile.password",
    "gender" : "profile.gender",
    "dob" : "profile.dob",
    "birth_time" : "profile.birth_time",
    "birth_place" : "profile.birth_place",
    "religion" : "profile.religion",
    "caste" : "profile.caste",
    "subcaste" : "profile.subcaste",
    "gothram" : "profile.gothram",
    "star" : "profile.star",
    "qualification" : "profile.qualification",
    "job" : "profile.job",
    "workplace" : "profile.workplace",
    "income" : "profile.income",
    "height" : "profile.height",
    "weight" : "profile.weight",
    "mother_tongue" : "profile.mother_tongue",
    "known_language" : "profile.known_language",
    "nativity" : "profile.nativity",
    "marital_status" : "profile.marital_status",
    "talents" : "profile.talents",
    "hobbies" : "profile.hobbies",
    "vehicle_driving" : "profile.vehicle_driving",
    "disabilities" : "profile.disabilities",
    "box11" : "profile.box11",
    "box12" : "profile.box12",
    "box13" : "profile.box13",
    "box14" : "profile.box14",
    "box15" : "profile.box15",
    "box16" : "profile.box16",
    "box17" : "profile.box17",
    "box18" : "profile.box18",
    "box19" : "profile.box19",
    "box110" : "profile.box110",
    "box111" : "profile.box111",
    "box112" : "profile.box112",
    "box21" : "profile.box21",
    "box22" : "profile.box22",
    "box23" : "profile.box23",
    "box24" : "profile.box24",
    "box25" : "profile.box25",
    "box26" : "profile.box26",
    "box27" : "profile.box27",
    "box28" : "profile.box28",
    "box29" : "profile.box29",
    "box210" : "profile.box210",
    "box211" : "profile.box211",
    "box212" : "profile.box212",
    "father_name" : "profile.father_name",
    "father_occupation" : "profile.father_occupation",
    "mother_name" : "profile.mother_name",
    "mother_occupation" : "profile.mother_occupation",
    "contact1" : "profile.contact1",
    "contact2" : "profile.contact2",
    "sibiling_count" : "profile.sibiling_count",
    "family_status" : "profile.family_status",
    "properties" : "profile.properties",
    "anydetails" : "profile.anydetails",
    "expected_qualification" : "profile.expected_qualification",
    "expected_place" : "profile.expected_place",
    "expected_income" : "profile.expected_income",
    "expected_caste" : "profile.expected_caste",
    "expected_subcaste" : "profile.expected_subcaste",
    "age_difference" : "profile.age_difference",
    "expected_height" : "profile.expected_height",
    "expected_weight" : "profile.expected_weight",
    "expectations" : "profile.expectations"
}